services:
  - type: web
    name: voyagery-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://guide-voyage-link-1.onrender.com/auth/google/callback
      - key: PORT
        value: 10000